"""Initialize tables

Revision ID: 6200c3a87c2d
Revises: 
Create Date: 2025-08-27 22:55:56.069311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# NEW
import sqlmodel
# END NEW



# revision identifiers, used by Alembic.
revision: str = '6200c3a87c2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peserta',
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sekolah', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peserta')
    # ### end Alembic commands ###
