"""Initialize tables

Revision ID: a216ffa662b9
Revises: 
Create Date: 2025-08-27 22:48:26.312015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# NEW
import sqlmodel
# END NEW



# revision identifiers, used by Alembic.
revision: str = 'a216ffa662b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesertadb',
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sekolah', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesertadb')
    # ### end Alembic commands ###
